[package]
name = "morse"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rstest = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
wav_io = "0.1.15"